[package]
name = "termkey-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
edition = "2021"
name = "tkey"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.71"
ctrlc = "3.2.5"
